import type { Metadata } from "next";
import { Jura, Onest } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const jura = Jura({
  subsets: ["latin"],
  variable: "--font-jura",
  display: "swap",
});

const onest = Onest({
  subsets: ["latin"],
  variable: "--font-onest",
  display: "swap",
});

const tomaso = localFont({
  src: [
    {
      path: "../../public/fonts/tomaso.woff2",
      weight: "normal",
      style: "normal",
    },
  ],
  variable: "--font-tomaso",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={`${onest.variable} ${jura.variable} ${tomaso.variable}`}>
      <head>
        <meta charSet="UTF-8" />
        <meta name="description" content={metadata.description as string} />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" type="image/svg+xml" href="/favicon.ico" />
        <meta name="robots" content="nofollow, noindex" />
        <title>{metadata.title as string}</title>
      </head>
      <body className="">
        <Header />
        {children}
      </body>
    </html>
  );
}
