import type { Metadata } from "next";
import "./globals.css";
import Header from "@/ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <meta charSet="UTF-8" />
        <meta name="description" content={metadata.description as string} />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <meta name="robots" content="nofollow, noindex" />
        <title>{metadata.title as string}</title>
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
